// /*
//   Auto-generated by Spline
// */

// import useSpline from '@splinetool/r3f-spline'
// import { OrthographicCamera } from '@react-three/drei'

// export default function Scene({ ...props }) {
//   const { nodes, materials } = useSpline('https://prod.spline.design/I6wUJ6xWxOKWlyF1/scene.splinecode')
//   return (
//     <>
//       <color attach="background" args={['#4b4d52']} />
//       <group {...props} dispose={null}>
//         <OrthographicCamera
//           name="Default Camera"
//           makeDefault={true}
//           far={50000}
//           near={-50000}
//           position={[0, -28, 1766.48]}
//           rotation={[0, 0, 0]}
//           scale={1}
//         >
//           <directionalLight
//             name="Default Directional Light"
//             intensity={0.75}
//             shadow-mapSize-width={1024}
//             shadow-mapSize-height={1024}
//             shadow-camera-near={-10000}
//             shadow-camera-far={100000}
//             position={[850000, 1300000, 1000000]}
//           />
//         </OrthographicCamera>
//         <group name="skull" scale={0.89}>
//           <group name="skull1" position={[-2.15, 38.22, 4.09]} rotation={[0.37, 0, 0]} scale={1.69}>
//             <group name="teeth" position={[1.67, -88.15, 125.51]} rotation={[-0.37, 0, 0]} scale={0.59}>
//               <group name="down" position={[-0.25, -43.96, -0.14]} rotation={[0.18, 0, -Math.PI]} scale={1}>
//                 <mesh
//                   name="teeth_1"
//                   geometry={nodes.teeth_1.geometry}
//                   material={materials['teeth_1 Material']}
//                   castShadow
//                   receiveShadow
//                   position={[79.18, 0.07, -3.88]}
//                   rotation={[-0.07, 0.16, 0.1]}
//                   scale={[1.09, 0.93, 0.59]}
//                 />
//                 <mesh
//                   name="teeth_2"
//                   geometry={nodes.teeth_2.geometry}
//                   material={materials['teeth_2 Material']}
//                   castShadow
//                   receiveShadow
//                   position={[40.19, -3.08, 0.71]}
//                   rotation={[-0.07, 0.08, 0.05]}
//                   scale={[1.09, 0.93, 0.59]}
//                 />
//                 <mesh
//                   name="teeth_3"
//                   geometry={nodes.teeth_3.geometry}
//                   material={materials['teeth_3 Material']}
//                   castShadow
//                   receiveShadow
//                   position={[0.9, -2.59, 1.18]}
//                   rotation={[-0.07, 0.01, -0.02]}
//                   scale={[1.09, 0.93, 0.59]}
//                 />
//                 <mesh
//                   name="teeth_4"
//                   geometry={nodes.teeth_4.geometry}
//                   material={materials['teeth_4 Material']}
//                   castShadow
//                   receiveShadow
//                   position={[-39.52, -2.02, 1.23]}
//                   rotation={[-0.07, 0.01, -0.04]}
//                   scale={[1.09, 0.93, 0.59]}
//                 />
//                 <mesh
//                   name="teeth_5"
//                   geometry={nodes.teeth_5.geometry}
//                   material={materials['teeth_5 Material']}
//                   castShadow
//                   receiveShadow
//                   position={[-79.31, 0.44, -1.45]}
//                   rotation={[-0.08, -0.23, -0.07]}
//                   scale={[1.09, 0.93, 0.59]}
//                 />
//               </group>
//               <group name="up" position={[-0.25, 5.81, -0.06]} scale={1}>
//                 <mesh
//                   name="teeth_11"
//                   geometry={nodes.teeth_11.geometry}
//                   material={materials.grey}
//                   castShadow
//                   receiveShadow
//                   position={[79.18, 0.07, -3.88]}
//                   rotation={[-0.07, 0.16, 0.1]}
//                   scale={[1.09, 0.93, 0.59]}
//                 />
//                 <mesh
//                   name="teeth_21"
//                   geometry={nodes.teeth_21.geometry}
//                   material={materials.grey}
//                   castShadow
//                   receiveShadow
//                   position={[40.31, -2.97, 2.23]}
//                   rotation={[-0.07, 0.08, 0.05]}
//                   scale={[1.09, 0.93, 0.59]}
//                 />
//                 <mesh
//                   name="teeth_31"
//                   geometry={nodes.teeth_31.geometry}
//                   material={materials.grey}
//                   castShadow
//                   receiveShadow
//                   position={[0.92, -2.42, 3.49]}
//                   rotation={[-0.07, 0.01, -0.02]}
//                   scale={[1.09, 0.93, 0.59]}
//                 />
//                 <mesh
//                   name="teeth_41"
//                   geometry={nodes.teeth_41.geometry}
//                   material={materials.grey}
//                   castShadow
//                   receiveShadow
//                   position={[-39.5, -1.83, 3.79]}
//                   rotation={[-0.07, 0.01, -0.04]}
//                   scale={[1.09, 0.93, 0.59]}
//                 />
//                 <mesh
//                   name="teeth_51"
//                   geometry={nodes.teeth_51.geometry}
//                   material={materials.grey}
//                   castShadow
//                   receiveShadow
//                   position={[-79.31, 0.44, -1.45]}
//                   rotation={[-0.08, -0.23, -0.07]}
//                   scale={[1.09, 0.93, 0.59]}
//                 />
//               </group>
//             </group>
//             <mesh
//               name="jaw"
//               geometry={nodes.jaw.geometry}
//               material={materials.grey}
//               castShadow
//               receiveShadow
//               position={[0.76, -169.86, 87.16]}
//               rotation={[-0.37, 0, 0]}
//               scale={[0.51, 0.59, 0.59]}
//             />
//             <mesh
//               name="head"
//               geometry={nodes.head.geometry}
//               material={materials.grey}
//               castShadow
//               receiveShadow
//               position={[0.15, -3.48, 8.86]}
//               rotation={[-0.32, 0, 0]}
//               scale={[0.85, 0.71, 0.85]}
//             />
//           </group>
//         </group>
//       </group>
//     </>
//   )
// }
